services:
  - type: web
    name: bert-sentiment-api
    env: python
    buildCommand: ""
    startCommand: "gunicorn bert_sentiment_api:app"
    envVars:
      - key: TRANSFORMERS_CACHE
        value: /var/cache/huggingface
